# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  workflow_dispatch:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set date
        id: set-date
        run: echo "::set-output name=date::$(date +%m%d)"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Create log directory
        run: mkdir -p "./day${{ steps.set-date.outputs.date }}/log"

      - name: Build
        run: |
          cd "./day${{ steps.set-date.outputs.date }}/main"
          go build -o ../main .

      - name: Output
        run: |
          cd "./day${{ steps.set-date.outputs.date }}/main"
          go test -v ./... >> ../log/today.log

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: today.log
          path: ./day${{ steps.set-date.outputs.date }}/log/day${{ steps.set-date.outputs.date }}.log
